#!/bin/sh

options="shutdown\nreboot"

option="$(echo $options | dmenu)"

case $option in
	shutdown) systemctl poweroff;;
	reboot) systemctl reboot;;
esac

echo '12000' > /sys/class/backlight/intel_backlight/brightness
